//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImplementCard
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Storage_id { get; set; }
        public Nullable<System.Guid> Implement_id { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Aviable { get; set; }
    
        public virtual Storage Storage { get; set; }
        public virtual Implement Implement { get; set; }
    }
}
