//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee : BaseClass
    {
        
        public Employee()
        {
            
        }
        public static Dictionary<Guid, Employee> Employees = new Dictionary<Guid, Employee>();
        private Guid _unitId;
        
        public Unit Unit_id { get; set; }
        public string Photo { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
    
       
    }
}
