//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImplementsCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImplementsCard()
        {
            this.ImplementMotions = new HashSet<ImplementMotion>();
        }
    
        public System.Guid Ic_id { get; set; }
        public Nullable<System.Guid> Implement_id { get; set; }
        public Nullable<System.Guid> Storage_id { get; set; }
        public Nullable<int> Amount { get; set; }
        public int Aviable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImplementMotion> ImplementMotions { get; set; }
        public virtual Implement Implement { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
