//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Implement : BaseClass
    {
        
        public Implement(String name, string type)
        {
            Name = name;
            Type = type;
        }

        public Dictionary<Guid,Implement> ImplementsDict = new Dictionary<Guid, Implement>();
        public string Type { get; set; }
        public string Name { get; set; }
        public float Weight { get; set; }
        public float Width { get; set; }
        public float Height { get; set; }
        public float Long { get; set; }
        public string Deskription { get; set; }
        public string Photo { get; set; }
    
       
    }
}
