//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImplementMotion : BaseClass
    {
        public ImplementMotion(ImplementsCard ic, Employee empl, int amount)
        {
            ImplementsCard = ic;
            Employee = empl;
            Amount = amount;
        }
        public enum MotionType { input=1, output=2, undefined=3 }
        private Guid ImplementCard_id;
        private Guid Employee_id;
        public MotionType Type { get; set; }
        public DateTime Date { get; set; }
        public int Amount { get; set; }        
    
        public  Employee Employee
        {
            get { return Employee.EmployeeDict[Employee_id]; }
            set
            {
                if (Employee.EmployeeDict.ContainsKey(value.Id))
                    Employee_id = value.Id;
            }
        }
        public  ImplementsCard ImplementsCard
        {
            get { return ImplementsCard.ImplementsCardDict[Employee_id]; }
            set
            {
                if (ImplementsCard.ImplementsCardDict.ContainsKey(value.Id))
                    ImplementCard_id = value.Id;
            }
        }
    }
}
