//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Implement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Implement()
        {
            this.ImplementsCards = new HashSet<ImplementsCard>();
        }
    
        public System.Guid I_id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public Nullable<float> Weight { get; set; }
        public Nullable<float> Width { get; set; }
        public Nullable<float> Height { get; set; }
        public Nullable<float> Long { get; set; }
        public string Deskription { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImplementsCard> ImplementsCards { get; set; }
    }
}
