//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    

    public partial class Overhead
    {
       
        public Overhead()
        {
            
        }
        public Dictionary<Guid, Overhead> Overheads = new Dictionary<Guid, Overhead>();
        private Guid _giverID;
        private Guid _reciverId;
        private Guid _storageID;
        public Employee Giver_id {
            get { return Employee.Employees[_giverID]; }
            set
            {
                if (Employee.Employees.ContainsKey(value.Id))
                    _giverID = value.Id;
            }
        }
        public Employee Reciver_id { get; set; }
        public Storage Storage_id { get; set; }
        public DateTime Data { get; set; }
        public string Type { get; set; }
    
        
    }
}
