//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person : BaseClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person(String fname,string lname,string phone="555-55-55")
        {
            First_name = fname;
            Last_name = lname;
            Phone = phone;            
        }
    
        
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Phone { get; set; }
        public LinkedList<Person> PersonsList = new LinkedList<Person>();
    }
}
