//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage : BaseClass
    {
       
        public Storage(Unit u, int capasity)
        {
            Unit = u;
            Capasity = capasity;
        }

        public Dictionary<Guid, Storage> StorageDict = new Dictionary<Guid, Storage>();
      
        public Guid Unit_id { get; set; }
        public int Capasity { get; set; }
        public string Adress { get; set; }

        public Unit Unit
        {
            get { return Unit.UnitDict[Unit_id]; }
            set
            {
                if (Unit.UnitDict.ContainsKey(Unit_id))
                    Unit_id = value.Id;
            }
        }

    }
}
