//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage : BaseClass
    {
        
        public Storage()
        {
            
        }

        public Dictionary<Guid, Storage> Storages = new Dictionary<Guid, Storage>();
        public Guid _unitId { get; set; }
        public int Capasity { get; set; }
        public string Adress { get; set; }
    
        
        public virtual Unit Unit { get; set; }
    }
}
