//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit : BaseClass
    {
        
        public Unit()
        {
            
        }
        public Dictionary<Guid, uint> Unints = new Dictionary<Guid, uint>();
       
        public string Name { get; set; }
        public Guid _headId { get; set; }  
        public virtual Employee HeadOfUnit { get; set; }
       
    }
}
