//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class User : BaseClass
    {
        public User(Employee empl, string login,string password,string access_rights="user")
        {
            Employee = empl;
            Login = login;
            Password = password;
        }
        public string Login { get; set; }
        public string Password { get; set; }
        private Guid Employee_id { get; set; }
        public string Access_rights { get;  set; }

        public Employee Employee
        {
            get { return Employee.EmployeeDict[Employee_id]; }
            set
            {
                if (Employee.EmployeeDict.ContainsKey(value.Id))
                    Employee_id = value.Id;
            }
        }
    }
}
