//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> Employee { get; set; }
        public string Access_rights { get; set; }
        public Nullable<System.Guid> Employee_id { get; set; }
    
        public virtual Employee Employee1 { get; set; }
    }
}
