//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarTable
    {
        public int ID { get; set; }
        public byte CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string ModelName { get; set; }
        public string ModelNumber { get; set; }
        public Nullable<double> Cost { get; set; }
        public string Description { get; set; }
        public string ImageCar { get; set; }
    }
}
